[package]
name = "empty"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
path = "src/lib.rs"

[dependencies.multiversx-sc]
version = "0.50.0"

[dev-dependencies]

[dev-dependencies.multiversx-sc-scenario]
version = "0.50.0"
